### ISSUE TITLE
v1.13 causes KSP 1.0.4 to freeze with exception with Procedural Parts and Real Fuels 

### ISSUE THREAD

**Issue by CorvusCorax** [KSP-RO/SolverEngines#15]
As discussed here: 

http://forum.kerbalspaceprogram.com/threads/106975-1-0-5-Procedural-Parts-Parts-the-way-you-want-em-v1-1-8-Nov-17?p=2303639&viewfull=1#post2303639

Upgrading SolverEngines (aka ModuleAnimateEmissive ) to 1.13 in CPAN causes KSP to not start if both Procedural Parts and Real Fuels are installed (and RealFuels requires ModuleAnimateEmissive)

Affected KSP version: 1.0.4
Affected Procedural parts version: v1.1.8 and older
Affected RealFuels version: rf-v10.7.2 and older

KSP log error:

```
[LOG 23:28:27.243] PartLoader: Compiling Part 'ProceduralParts/Parts/ZOtherMods/RFSRB/proceduralSRBRealFuels'
[LOG 23:28:27.281] Added sound_rocket_hard to FXGroup running
[ERR 23:28:27.290] Cannot find a PartModule of typename 'ModuleFuelTanks'

[ERR 23:28:27.290] Cannot find a PartModule of typename 'ModuleEngineConfigs'

[ERR 23:28:27.290] Cannot find a PartModule of typename 'ModuleEnginesRF'

[LOG 23:28:27.292] OnLoad
[LOG 23:28:27.293] OnLoad end
[LOG 23:28:27.309] *PP* InitializeBells
[EXC 23:28:27.311] ArgumentException: Unable to find engine-like module
        KSPAPIExtensions.Utils.EngineWrapper..ctor (.Part part)^M
        ProceduralParts.ProceduralSRB.get_Engine ()^M
        ProceduralParts.ProceduralSRB.InitModulesFromBell ()^M
        ProceduralParts.ProceduralSRB.InitializeBells ()^M
        ProceduralParts.ProceduralSRB.GetInfo ()^M
        PartLoader.CompilePartInfo (.AvailablePart newPartInfo, .Part part)^M
        PartLoader+^V^E.MoveNext ()
```

KSPAPIExtensions.dll comes with Procedural Parts and seeks a module of name "ModuleEngines" or "ModuleEnginesFX" in any procedural engine (which is only the procedural SRB currently)

Realism Overhaul as well as  other Configuration helper modules for RealFuels modify the procedural SRB in the following way:

```
@PART[proceduralSRBRealFuels,proceduralTankHRB] 
...
@MODULE[ModuleEngines*] 
    { 
        @name = ModuleEnginesRF
    } 
```

or similar.

It seems that this modification causes ProceduralParts to no longer find the "ModuleEngines" section it seeks and KSP freezes when the procedural SRB is being initialized

Except, with SolverEngines downgraded to v1.11 this bug does not appear.

**Comment by NathanKell** [comment]
Please use the correct version of the plugin. If on the ksp 1.0.4, the most
recent version of solver and mae is 1.11. RF 10.7.2.
If on 1.0.5, ModuleAnimateEmissive no longer exists, solver 1.13, RF 10.8.1.

Sent by my thumbs, slowly.

**Comment by CorvusCorax** [comment]
thanks for the update, yeah I just saw in the code that 1.13 is simply incompatible to 1.0.4.
problem is CKAN, the metadata doesn't forbid installation on v1.13 on 1.0.4 so CKAN will auto-update it, breaking all 1.0.4 installations

**Comment by NathanKell** [comment]
Please raise an issue on their repo then, I am away and cannot fix it from
here.

Sent by my thumbs, slowly.

**Comment by Gnurfos** [comment]
Hello,

I don't know whether it is the same problem but it looks very similar: although release 1.15 does not seem recent on github, CKAN offered me to update to 1.15 (along with 2 other mods I don't remember) only a few hours ago. After I did, KSP froze on loading with errors similar as those posted here. Downgrading (just SolverEngines) to 1.14 solved the issue.

Cheers

**Comment by jenden0** [comment]
I can confirm the same behavior.  After CKAN updated SmokeScren, ProgressParser, SolverEngines, ContractsWindowPlus, RP-0, and AdvancedJetEngine today KSP froze with errors above until I swapped out the SolverEngines 1.15 dll with the 1.14 dll.

**Comment by blowfishpro** [comment]
@NathanKell Have you released an update for RealFuels yet?

If not, @Gnurfos and @jenden0 if you're using RealFuels, then stick with SolverEngines 1.14 and AJE 2.5.4 until a RealFuels update is released.

**Comment by Gnurfos** [comment]
Yes I'm using RealFuels. Keeping AJE 2.6 does not exhibit the same load freezing behaviour, apparently (but maybe causes problems in-game with jets, I didn't try). The thing is, I think this mods combination comes from RP-0 and/or RO, so it might impact a lot of people.

**Comment by NathanKell** [comment]
I was going to, but it got late fast and I forgot. :( Doing so ASAP today.

**Comment by Gnurfos** [comment]
Thanks for the effort, the new versions seem to work well together !

**Comment by blowfishpro** [comment]
I think this is resolved now
