### ISSUE TITLE
Debug spam

### ISSUE THREAD

**Issue by ABZB** [KSP-RO/SolverEngines#16]
I am getting Spam of 
"Ambient density does not obey the gas law for vessel [name of root part]" in the debug log, to the point where KSP is severely lagging.... Is it possible that the current release does not have that commented out? I saw that that line is commented out in the current code...

**Comment by blowfishpro** [comment]
That shouldn't be happening on 1.14 (the latest).  Do you have that version?

**Comment by ABZB** [comment]
My mistake, I kept digging based on that, & I found that some previous Realfuels download had come with a SolverEngines module (in RealFuels/Plugins/). 

[My RF install is not through CKAN, as CKAN still insists that RF conflicts with IFS Fuel Switch, and I have a lot of mods that have the latter as a dependency, and none that depend on the former.]
