### ISSUE TITLE
The "CLAMP = float.MaxValue" hack is breaking current version of TCA.

### ISSUE THREAD

**Issue by allista** [KSP-RO/SolverEngines#18]
**FYI:**

Here's [the line](https://github.com/KSP-RO/SolverEngines/blob/eba89da74767fb66ea96661a5950fa52233e8822/SolverEngines/EngineModule.cs#L572) I'm referencing to.

ThrottleControlledAvionics uses the code from ModuleEngines.ModifyFlow() [to calculate the fuel **flow modifier**](https://github.com/qfeys/ThrottleControlledAvionics/blob/master/EngineWrapper.cs#L255). This hack effectively sets the modifier to MaxValue as well, which causes the calculated thrust to be _Infinity_.

Right now I've added a workaround: the CLAMP is used only when it is less than 1. But maybe you could handle flameouts in a less radical way that does not generate such unexpected values? :) Could setting CLAMP to 1 do the same trick?

**Comment by lamont-granquist** [comment]
I also just ran into this breaking some code I wrote for MechJeb.

**Comment by blowfishpro** [comment]
NathanKell wrote this code but has been pretty inactive lately.  I'll try to understand why this was done this way if I have time soon.

**Comment by Starwaster** [comment]
According to the comments, that whole bit was a dirty hack to get around ModuleEngineFX.CanStart() not being virtual ... except that currently it IS so what needs to happen is that an override CanStart method needs to be written which has a check that flameout is true (and returns that if necessary) and remove the two lines that tamper with CLAMP.

**Comment by Starwaster** [comment]
This will be addressed in the update for KSP 1.6

**Comment by DRVeyl** [comment]
Fixed with https://github.com/KSP-RO/SolverEngines/commit/2583d99afcbda633b4dbc09ce30147cb41a20cfc
