### ISSUE TITLE
ASL/Vac thrust

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/SolverEngines#27]
@blowfishpro despite the new release supposedly fixing this issue, I am still seeing RF give ASL thrust values for engines instead of the Vac ones in the editor.

Making the changes directly to the RF source to fix this works but I know you wanted to address the issue in solverengines instead and it doesn't appear to be working.

**Comment by blowfishpro** [comment]
The fix was partially in RF and partially in SolverEngines, but it requires a new release of RF to work.  @Starwaster still wanted to make some changes so I haven't done that yet though.

**Comment by raidernick** [comment]
ok thanks for the clarification
