### ISSUE TITLE
Typo in engine database name

### ISSUE THREAD

**Issue by blowfishpro** [KSP-RO/SolverEngines#32]
Good thing it's a constant I guess.  Still, should be fixed.

https://github.com/KSP-RO/SolverEngines/blob/4953e9d60c6d3be10ee9df0c5987379d8ce883be/SolverEngines/EngineFitting/EngineDatabase.cs#L36

**Comment by DRVeyl** [comment]
Fixed with https://github.com/KSP-RO/SolverEngines/commit/2583d99afcbda633b4dbc09ce30147cb41a20cfc (2 years ago)
