### ISSUE TITLE
Expose numeric field engineTemp?

### ISSUE THREAD

**Issue by MOARdV** [KSP-RO/SolverEngines#33]
I'm adding support in MOARdV's Avionics Systems to interact with AJE engines, starting with propeller engines.  One value that I'd like to provide is the engine temperature in ModuleEnginesSolver.  However, it's protected.  Would it be possible to add a public property that allows me to read that value so that I don't need to read the temperature string UI field and convert it to a double?

**Comment by Starwaster** [comment]
Only a year late but this will be done via ModuleEnginesSolver.GetEngineTemp in the next update (for KSP 1.6)

**Comment by DRVeyl** [comment]
Looks like this issue is completed?  (Ended up here looking specifically for getting the engine temp from SolverEngines)

**Comment by DRVeyl** [comment]
Fixed with https://github.com/KSP-RO/SolverEngines/commit/2583d99afcbda633b4dbc09ce30147cb41a20cfc
