### ISSUE TITLE
SolverEngines toolbar GUI

### ISSUE THREAD

**Issue by A1Ch1** [KSP-RO/SolverEngines#9]
When not using the blizzy bar, the SE GUI appears in the stock toolbar. If the blizzy toolbar is installed, the SE GUI disappears from the stock toolbar as intended, but doesn't appear as an option for the blizzy bar.

**Comment by NathanKell** [comment]
I thought this was fixed in the current release...You're on the current release, right?
Tagging @blowfishpro

**Comment by blowfishpro** [comment]
There was a NRE preventing it from showing up in the Blizzy toolbar.  I implemented a fix a couple of days ago which seemed to work when I tested it.

**Comment by NathanKell** [comment]
Yeah, checking the current code in git I saw no bad characters--and that code was released in 1.8. So that's why I'm confused.

**Comment by A1Ch1** [comment]
Hmm, yeah, using SolverEngines 1.8 and Toolbar 1.7.9. I'll check again, maybe I just missed it...

**Comment by A1Ch1** [comment]
You're right, it's right there at the top of the list. Don't know how I could have overlooked it. My bad :)

**Comment by NathanKell** [comment]
No probs, glad it's sorted. :)

**Comment by A1Ch1** [comment]
Scratch that, the SolverEngines GUI disappears after liftoff...

**Comment by blowfishpro** [comment]
Can't replicate.  Could you provide more information?

**Comment by A1Ch1** [comment]
Yes, testing

**Comment by A1Ch1** [comment]
https://youtu.be/ppm8AXtIh1M?t=55s

SolverEngines button disappears from toolbar at 43 seconds after launch (1:05 in video), although the open SolverEngines GUI itself remains. SolverEngines also disappears from Configure Visible Buttons

Output log: 
https://www.dropbox.com/s/dyuz3fj2h37nwu6/output_log.txt?dl=0

**Comment by blowfishpro** [comment]
Okay, I figured out why this is.  It happens when another vessel (e.g. a lower stage) goes out of physics range, and its VesselModule components are destroyed.  I'll work on fixing this.

This is a reminder why you should never blindly copy someone else's code without question, even someone you trust to write good code (ferram4).  It appears that this happens in FAR too.

**Comment by A1Ch1** [comment]
:+1: Thank you!

**Comment by blowfishpro** [comment]
Should be fixed now
